# Generated by Django 2.0.1 on 2018-02-16 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20180213_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Mysubscriber', 'verbose_name_plural': 'A lot of Subscribers'},
        ),
    ]
